### ISSUE TITLE
How do I install this

### ISSUE THREAD

**Issue by BudgieIsEpic2** [matcool/CocosExplorer#8]
Tried putting the master file in the game folder, Didn't work, Reset the game atleast 5 times. Nothing is working

**Comment by GavinGoGaming** [comment]
Its a dll. You need an injector.
Heres a free one I use called Lunar Injector, Its open source and found on UnknownCheats [here](https://www.unknowncheats.me/forum/c-/424615-lunar-injector-safe-easy-dll-injector.html)

[LunarInjector.zip](https://github.com/matcool/CocosExplorer/files/13837003/LunarInjector_.unknowncheats.me._.zip)
